# OSX specific aliases
alias brewup="brew update && brew upgrade && brew prune && brew cleanup && brew doctor"
alias brewrelink='brew list -1 | while read line; do brew unlink $line; brew link --force $line; done'

# vim: set ft=sh:
