# OSX specific bashrc
# shellcheck source=/dev/null
# SC1090 is not able to follow sourced files and I don't care in bashrc case

# enables coloring of your terminal
export CLICOLOR=1
# how to color specific items
export LSCOLORS=ExFxBxDxCxegedabagacad

# let's install app using brew cask in user space
export HOMEBREW_CASK_OPTS="--appdir=${HOME}/Applications"

if [ -e "${HOME}/.iterm2_shell_integration.bash" ]; then
    source "${HOME}/.iterm2_shell_integration.bash"
fi

source ~/.osx/bash_aliases

# vim: set ft=sh:
